spring:
  application:
    name: store-cloud-service-notify

security.basic.enabled: false

server:
  port: 8516

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# REDIS (RedisProperties)
redis:
  cluster: false
  single-host: 127.0.0.1
  single-port: 6379
  password:
